apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-autoscaling
  namespace: desenvolvimento-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: frontend-deployment
  minReplicas: 4
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60